### ISSUE TITLE
SQL Server

### ISSUE THREAD

**Issue by tcartwright** [andygrunwald/your-connection-deserves-a-name#3]
https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.applicationname?view=dotnet-plat-ext-5.0

Here is how to do it for SQL Server, and preach on! I have been trying to get everyone on board this train for years that I work with.

**Comment by andygrunwald** [comment]
Hey @tcartwright,
thanks a lot for this hint. Pretty cool that MSSQL also supports this.

I am not that familiar with C#/.net.
As far as I can see, the [go-mssqldb] driver also supports this: https://github.com/denisenkom/go-mssqldb#the-connection-string-can-be-specified-in-one-of-three-formats

If I have a bit of time, I will play around with a prototype on this.
I am also happy to accept any PR in this direction.

**Comment by tcartwright** [comment]
I can easily whip up a couple of different connection string examples for you. At my current job we have a library that gets our connections from an encrypted service. I recently added code that inspected the stack trace and retrieved the lowest level application that belonged to us and set that to the application name if it was empty. Wasn't 100% foolproof, but it provided a lot of application names that were missing before.

@andygrunwald  Give me some time, I am quite busy atm. Will try to whip you up a PR soon enough.

**Comment by andygrunwald** [comment]
Sounds good, thanks @tcartwright.
