### ISSUE TITLE
Add connection naming example for Oracle Database

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/your-connection-deserves-a-name#5]
Oracle supports `dbms_application_info`.
This can assign `client_info` to a session.

See:
* [Oracle dbms_application_info tips](http://www.dba-oracle.com/t_dbms_application_info.htm)
* [DBMS_APPLICATION_INFO : For Code Instrumentation](https://oracle-base.com/articles/8i/dbms_application_info#set_client_info)
* [14 DBMS_APPLICATION_INFO](https://docs.oracle.com/cd/B19306_01/appdev.102/b14258/d_appinf.htm#CHECEIEB)

Go client libraries:
- https://github.com/godror/godror
- https://github.com/sijms/go-ora

**Comment by andygrunwald** [comment]
See also https://franckpachot.medium.com/you-should-set-ocsid-clientid-e00cb81ed7e2

**Comment by andygrunwald** [comment]
From quick research, there is no public oracle image available. A license is required.

**Comment by gvenzl** [comment]
Hey @andygrunwald, I was just about to leave you a comment about the same here.

GODROR offers a wrapper around `DBMS_APPLICATION_INFO` with the [TraceTag](https://pkg.go.dev/github.com/godror/godror#TraceTag) struct, see: https://godror.github.io/godror/doc/logging.html#-tracing

In comparison, the Python driver (cx_Oracle) makes it even simpler by just exposing these as attributes to a connection, e.g: https://cx-oracle.readthedocs.io/en/latest/api_manual/connection.html#Connection.client_identifier.

You will find that there are even [a couple of more attributes that Oracle Database offers, such as module info and action](https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_APPLICATION_INFO.html#GUID-6F1765B9-B716-4A44-AFB7-7C2608E080A4).
This allows users to specify more than just "App X", for example, an application could use the module information to share information whereabouts in the app the call comes from, say a specific class or logical part of the app.
The action field could be set for individual tasks even, such as "storing customer information".
That way an application could leverage the built-in tracing capabilities from Oracle to help diagnose, e.g., even where in the app slow running SQL statement comes from.

> From quick research, there is no public oracle image available. A license is required.

That is not true, you can use [Oracle XE](https://oracle.com/xe) entirely free of charge.
You can also pull the official Oracle XE image via `docker pull container-registry.oracle.com/database/express:latest`.
Likewise, you can pull [my XE image](https://hub.docker.com/r/gvenzl/oracle-xe) via `docker pull gvenzl/oracle-xe:18-slim`.

**Comment by andygrunwald** [comment]
@gvenzl Thanks a lot. That information is really useful for me.

> Likewise, you can pull my XE image via `docker pull gvenzl/oracle-xe:18-slim`.

Whats the difference between your image and `container-registry.oracle.com/database/express:latest`?
PS: Thanks for pointing me to the docker express imagee.

**Comment by gvenzl** [comment]
Smaller and faster to startup, mostly. I put a couple of more parameters into mine as well, it's the one I'm planning to use for `csv2db` GitHub Actions. But, for example, `gvenzl/oracle-xe:18-full` is practically the same as the one on container-registry.oracle.com (besides the additional parameters).

**Comment by andygrunwald** [comment]
Thanks for the context.

**Comment by andygrunwald** [comment]
Hey @gvenzl,
thanks for your input. I added an Oracle example for Go and Python in https://github.com/andygrunwald/your-connection-deserves-a-name/pull/7
